In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [23]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print arr1
data2 = [range(1, 5), range(5, 9)]
print data2
arr2 = np.array(data2)
print arr2
arr2.tolist()

arr1.dtype
arr2.dtype
arr2.ndim
arr2.shape
arr2.size
len(arr2)

[ 6.   7.5  8.   0.   1. ]
[[1, 2, 3, 4], [5, 6, 7, 8]]
[[1 2 3 4]
 [5 6 7 8]]


2

In [21]:
np.zeros(10)
np.zeros((3, 6))
np.ones(10)
np.linspace(0, 1, 5)
np.logspace(0, 3, 4)

array([    1.,    10.,   100.,  1000.])

In [31]:
int_array = np.arange(5)
print int_array
float_array = int_array.astype(float)
print float_array

[0 1 2 3 4]
[ 0.  1.  2.  3.  4.]


In [47]:
arr2[:,0:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [65]:
arr = np.arange(10)
arr_view = arr[5:8]
arr_view[:] = 13
arr
#arr_view

array([ 0,  1,  2,  3,  4, 13, 13, 13,  8,  9])

In [73]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob'])
names != 'Bob'
(names == 'Bob') | (names == 'Will') 
names[names != 'Bob'] = 'Joe'
names
np.unique(names)  

array(['Bob', 'Joe'], 
      dtype='|S4')

In [115]:
nums = np.arange(5)
#nums = nums*10 
#nums = np.sqrt(nums) 
#nums
np.floor(nums)  
np.isnan(nums) 
nums + np.arange(5) 
np.maximum(nums, np.array([1, -2, 3, -4, 5]))

array([1, 1, 3, 3, 5])

In [ ]:
rnd = np.random.randn(4, 2)
print rnd
rnd.mean()
rnd.std()
rnd.argmin() 
rnd.sum()
rnd.sum(axis=0)
rnd.sum(axis=1) 

In [ ]:
N = 50

x = np.random.rand(N)
y = np.random.rand(N)
colors = np.random.rand(N)
area =30+(70*np.random.rand(N))

plt.scatter(x, y, s=area, c=colors,)
plt.show()

In [47]:
rnd = np.random.randn(4, 2)
print rnd
#np.where(rnd > 0, 2, -2) 
#np.where(rnd > 0, 2, rnd)
(rnd > 0).sum() 
(rnd > 0).any()
(rnd > 0).all() 

[[-0.12546674 -0.26868097]
 [-0.93607027 -1.55431776]
 [-0.71129061  0.84883791]
 [-0.33194833 -1.8580505 ]]


False

In [56]:
nums = np.arange(32).reshape(8, 4)

print nums

nums.T 
nums.flatten()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [17]:
np.random.seed(12234)
np.random.rand(2, 3) 
np.random.randn(10) 
np.random.randint(0, 2, 10)


array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1])